## HBase 配置
spring:
  data:
    hbase:
      config:
        zookeeper:
          quorum: centos1
        rootdir: file:///workspace/hbase
        fs:
          default:
            name: file:///workspace/hbase