server:
  port: 8091

netty:
  #netty监听链接地址
  port: 5000

dubbo:
  application:
    name: chat-dubbo
    qosEnable: false
  protocol:
    name: dubbo
    port: 20881

  registy:
    id: register
    address: zookeeper://localhost:2181
  consumer:
    timeout: 5000


spring:
  profiles:
    active: work
  aop:
    proxy-target-class: true
#redis 相关配置
  redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
        # 连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0

  datasource:
    url: jdbc:mysql://localhost:3306/iot
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      initial-size: 10
      max-active: 20
      min-idle: 8
# mybatis配置相关
mybatis:
  type-aliases-package: com.hailin.iot.common.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true

#idgen的配置
idgen:
  redisUrl: redis://127.0.0.1:6379/1
  port: 6379
