// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.protoc

package com.hailin.iot.common.protoc;

public final class ChatMessageBuf {
  private ChatMessageBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hailin.iot.common.protoc.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>string acceptUser = 1;</code>
     * @return The acceptUser.
     */
    java.lang.String getAcceptUser();
    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>string acceptUser = 1;</code>
     * @return The bytes for acceptUser.
     */
    com.google.protobuf.ByteString
        getAcceptUserBytes();

    /**
     * <pre>
     *消息类型 群聊,私聊,朋友圈
     * </pre>
     *
     * <code>int32 messageBit = 2;</code>
     * @return The messageBit.
     */
    int getMessageBit();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.hailin.iot.common.protoc.ChatMessage}
   */
  public  static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hailin.iot.common.protoc.ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      acceptUser_ = "";
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              acceptUser_ = s;
              break;
            }
            case 16: {

              messageBit_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailin.iot.common.protoc.ChatMessageBuf.internal_static_com_hailin_iot_common_protoc_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailin.iot.common.protoc.ChatMessageBuf.internal_static_com_hailin_iot_common_protoc_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.class, com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.Builder.class);
    }

    public static final int ACCEPTUSER_FIELD_NUMBER = 1;
    private volatile java.lang.Object acceptUser_;
    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>string acceptUser = 1;</code>
     * @return The acceptUser.
     */
    public java.lang.String getAcceptUser() {
      java.lang.Object ref = acceptUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acceptUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>string acceptUser = 1;</code>
     * @return The bytes for acceptUser.
     */
    public com.google.protobuf.ByteString
        getAcceptUserBytes() {
      java.lang.Object ref = acceptUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBIT_FIELD_NUMBER = 2;
    private int messageBit_;
    /**
     * <pre>
     *消息类型 群聊,私聊,朋友圈
     * </pre>
     *
     * <code>int32 messageBit = 2;</code>
     * @return The messageBit.
     */
    public int getMessageBit() {
      return messageBit_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAcceptUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, acceptUser_);
      }
      if (messageBit_ != 0) {
        output.writeInt32(2, messageBit_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAcceptUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, acceptUser_);
      }
      if (messageBit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageBit_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage)) {
        return super.equals(obj);
      }
      com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage other = (com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage) obj;

      if (!getAcceptUser()
          .equals(other.getAcceptUser())) return false;
      if (getMessageBit()
          != other.getMessageBit()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCEPTUSER_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptUser().hashCode();
      hash = (37 * hash) + MESSAGEBIT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBit();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hailin.iot.common.protoc.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hailin.iot.common.protoc.ChatMessage)
        com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailin.iot.common.protoc.ChatMessageBuf.internal_static_com_hailin_iot_common_protoc_ChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailin.iot.common.protoc.ChatMessageBuf.internal_static_com_hailin_iot_common_protoc_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.class, com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.Builder.class);
      }

      // Construct using com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        acceptUser_ = "";

        messageBit_ = 0;

        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailin.iot.common.protoc.ChatMessageBuf.internal_static_com_hailin_iot_common_protoc_ChatMessage_descriptor;
      }

      @java.lang.Override
      public com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage getDefaultInstanceForType() {
        return com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage build() {
        com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage buildPartial() {
        com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage result = new com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage(this);
        result.acceptUser_ = acceptUser_;
        result.messageBit_ = messageBit_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage) {
          return mergeFrom((com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage other) {
        if (other == com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage.getDefaultInstance()) return this;
        if (!other.getAcceptUser().isEmpty()) {
          acceptUser_ = other.acceptUser_;
          onChanged();
        }
        if (other.getMessageBit() != 0) {
          setMessageBit(other.getMessageBit());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object acceptUser_ = "";
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>string acceptUser = 1;</code>
       * @return The acceptUser.
       */
      public java.lang.String getAcceptUser() {
        java.lang.Object ref = acceptUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          acceptUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>string acceptUser = 1;</code>
       * @return The bytes for acceptUser.
       */
      public com.google.protobuf.ByteString
          getAcceptUserBytes() {
        java.lang.Object ref = acceptUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acceptUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>string acceptUser = 1;</code>
       * @param value The acceptUser to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        acceptUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>string acceptUser = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptUser() {
        
        acceptUser_ = getDefaultInstance().getAcceptUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>string acceptUser = 1;</code>
       * @param value The bytes for acceptUser to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        acceptUser_ = value;
        onChanged();
        return this;
      }

      private int messageBit_ ;
      /**
       * <pre>
       *消息类型 群聊,私聊,朋友圈
       * </pre>
       *
       * <code>int32 messageBit = 2;</code>
       * @return The messageBit.
       */
      public int getMessageBit() {
        return messageBit_;
      }
      /**
       * <pre>
       *消息类型 群聊,私聊,朋友圈
       * </pre>
       *
       * <code>int32 messageBit = 2;</code>
       * @param value The messageBit to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBit(int value) {
        
        messageBit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型 群聊,私聊,朋友圈
       * </pre>
       *
       * <code>int32 messageBit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageBit() {
        
        messageBit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hailin.iot.common.protoc.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:com.hailin.iot.common.protoc.ChatMessage)
    private static final com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage();
    }

    public static com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      @java.lang.Override
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailin.iot.common.protoc.ChatMessageBuf.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hailin_iot_common_protoc_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hailin_iot_common_protoc_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ChatMessage.protoc\022\034com.hailin.iot.com" +
      "mon.protoc\"F\n\013ChatMessage\022\022\n\nacceptUser\030" +
      "\001 \001(\t\022\022\n\nmessageBit\030\002 \001(\005\022\017\n\007content\030\003 \001" +
      "(\tB\020B\016ChatMessageBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hailin_iot_common_protoc_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hailin_iot_common_protoc_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hailin_iot_common_protoc_ChatMessage_descriptor,
        new java.lang.String[] { "AcceptUser", "MessageBit", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
