// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.protoc

package com.hailin.iot.common.protoc;

public final class MessageBuf {
  private MessageBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hailin.iot.common.protoc.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送方
     * </pre>
     *
     * <code>optional string sendUser = 1;</code>
     */
    java.lang.String getSendUser();
    /**
     * <pre>
     *发送方
     * </pre>
     *
     * <code>optional string sendUser = 1;</code>
     */
    com.google.protobuf.ByteString
        getSendUserBytes();

    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>optional string acceptUser = 2;</code>
     */
    java.lang.String getAcceptUser();
    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>optional string acceptUser = 2;</code>
     */
    com.google.protobuf.ByteString
        getAcceptUserBytes();

    /**
     * <pre>
     *消息类型 群聊,私聊,朋友圈
     * </pre>
     *
     * <code>optional int32 messageBit = 3;</code>
     */
    int getMessageBit();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.hailin.iot.common.protoc.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hailin.iot.common.protoc.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      sendUser_ = "";
      acceptUser_ = "";
      messageBit_ = 0;
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sendUser_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              acceptUser_ = s;
              break;
            }
            case 24: {

              messageBit_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailin.iot.common.protoc.MessageBuf.internal_static_com_hailin_iot_common_protoc_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailin.iot.common.protoc.MessageBuf.internal_static_com_hailin_iot_common_protoc_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailin.iot.common.protoc.MessageBuf.Message.class, com.hailin.iot.common.protoc.MessageBuf.Message.Builder.class);
    }

    public static final int SENDUSER_FIELD_NUMBER = 1;
    private volatile java.lang.Object sendUser_;
    /**
     * <pre>
     *发送方
     * </pre>
     *
     * <code>optional string sendUser = 1;</code>
     */
    public java.lang.String getSendUser() {
      java.lang.Object ref = sendUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送方
     * </pre>
     *
     * <code>optional string sendUser = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSendUserBytes() {
      java.lang.Object ref = sendUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCEPTUSER_FIELD_NUMBER = 2;
    private volatile java.lang.Object acceptUser_;
    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>optional string acceptUser = 2;</code>
     */
    public java.lang.String getAcceptUser() {
      java.lang.Object ref = acceptUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acceptUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收方
     * </pre>
     *
     * <code>optional string acceptUser = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAcceptUserBytes() {
      java.lang.Object ref = acceptUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBIT_FIELD_NUMBER = 3;
    private int messageBit_;
    /**
     * <pre>
     *消息类型 群聊,私聊,朋友圈
     * </pre>
     *
     * <code>optional int32 messageBit = 3;</code>
     */
    public int getMessageBit() {
      return messageBit_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSendUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sendUser_);
      }
      if (!getAcceptUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, acceptUser_);
      }
      if (messageBit_ != 0) {
        output.writeInt32(3, messageBit_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSendUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sendUser_);
      }
      if (!getAcceptUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, acceptUser_);
      }
      if (messageBit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, messageBit_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailin.iot.common.protoc.MessageBuf.Message)) {
        return super.equals(obj);
      }
      com.hailin.iot.common.protoc.MessageBuf.Message other = (com.hailin.iot.common.protoc.MessageBuf.Message) obj;

      boolean result = true;
      result = result && getSendUser()
          .equals(other.getSendUser());
      result = result && getAcceptUser()
          .equals(other.getAcceptUser());
      result = result && (getMessageBit()
          == other.getMessageBit());
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SENDUSER_FIELD_NUMBER;
      hash = (53 * hash) + getSendUser().hashCode();
      hash = (37 * hash) + ACCEPTUSER_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptUser().hashCode();
      hash = (37 * hash) + MESSAGEBIT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBit();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.MessageBuf.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailin.iot.common.protoc.MessageBuf.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hailin.iot.common.protoc.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hailin.iot.common.protoc.Message)
        com.hailin.iot.common.protoc.MessageBuf.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailin.iot.common.protoc.MessageBuf.internal_static_com_hailin_iot_common_protoc_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailin.iot.common.protoc.MessageBuf.internal_static_com_hailin_iot_common_protoc_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailin.iot.common.protoc.MessageBuf.Message.class, com.hailin.iot.common.protoc.MessageBuf.Message.Builder.class);
      }

      // Construct using com.hailin.iot.common.protoc.MessageBuf.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sendUser_ = "";

        acceptUser_ = "";

        messageBit_ = 0;

        content_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailin.iot.common.protoc.MessageBuf.internal_static_com_hailin_iot_common_protoc_Message_descriptor;
      }

      public com.hailin.iot.common.protoc.MessageBuf.Message getDefaultInstanceForType() {
        return com.hailin.iot.common.protoc.MessageBuf.Message.getDefaultInstance();
      }

      public com.hailin.iot.common.protoc.MessageBuf.Message build() {
        com.hailin.iot.common.protoc.MessageBuf.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hailin.iot.common.protoc.MessageBuf.Message buildPartial() {
        com.hailin.iot.common.protoc.MessageBuf.Message result = new com.hailin.iot.common.protoc.MessageBuf.Message(this);
        result.sendUser_ = sendUser_;
        result.acceptUser_ = acceptUser_;
        result.messageBit_ = messageBit_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailin.iot.common.protoc.MessageBuf.Message) {
          return mergeFrom((com.hailin.iot.common.protoc.MessageBuf.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailin.iot.common.protoc.MessageBuf.Message other) {
        if (other == com.hailin.iot.common.protoc.MessageBuf.Message.getDefaultInstance()) return this;
        if (!other.getSendUser().isEmpty()) {
          sendUser_ = other.sendUser_;
          onChanged();
        }
        if (!other.getAcceptUser().isEmpty()) {
          acceptUser_ = other.acceptUser_;
          onChanged();
        }
        if (other.getMessageBit() != 0) {
          setMessageBit(other.getMessageBit());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailin.iot.common.protoc.MessageBuf.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailin.iot.common.protoc.MessageBuf.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sendUser_ = "";
      /**
       * <pre>
       *发送方
       * </pre>
       *
       * <code>optional string sendUser = 1;</code>
       */
      public java.lang.String getSendUser() {
        java.lang.Object ref = sendUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sendUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送方
       * </pre>
       *
       * <code>optional string sendUser = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSendUserBytes() {
        java.lang.Object ref = sendUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送方
       * </pre>
       *
       * <code>optional string sendUser = 1;</code>
       */
      public Builder setSendUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sendUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方
       * </pre>
       *
       * <code>optional string sendUser = 1;</code>
       */
      public Builder clearSendUser() {
        
        sendUser_ = getDefaultInstance().getSendUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方
       * </pre>
       *
       * <code>optional string sendUser = 1;</code>
       */
      public Builder setSendUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sendUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object acceptUser_ = "";
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>optional string acceptUser = 2;</code>
       */
      public java.lang.String getAcceptUser() {
        java.lang.Object ref = acceptUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          acceptUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>optional string acceptUser = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAcceptUserBytes() {
        java.lang.Object ref = acceptUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acceptUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>optional string acceptUser = 2;</code>
       */
      public Builder setAcceptUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        acceptUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>optional string acceptUser = 2;</code>
       */
      public Builder clearAcceptUser() {
        
        acceptUser_ = getDefaultInstance().getAcceptUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方
       * </pre>
       *
       * <code>optional string acceptUser = 2;</code>
       */
      public Builder setAcceptUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        acceptUser_ = value;
        onChanged();
        return this;
      }

      private int messageBit_ ;
      /**
       * <pre>
       *消息类型 群聊,私聊,朋友圈
       * </pre>
       *
       * <code>optional int32 messageBit = 3;</code>
       */
      public int getMessageBit() {
        return messageBit_;
      }
      /**
       * <pre>
       *消息类型 群聊,私聊,朋友圈
       * </pre>
       *
       * <code>optional int32 messageBit = 3;</code>
       */
      public Builder setMessageBit(int value) {
        
        messageBit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型 群聊,私聊,朋友圈
       * </pre>
       *
       * <code>optional int32 messageBit = 3;</code>
       */
      public Builder clearMessageBit() {
        
        messageBit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hailin.iot.common.protoc.Message)
    }

    // @@protoc_insertion_point(class_scope:com.hailin.iot.common.protoc.Message)
    private static final com.hailin.iot.common.protoc.MessageBuf.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailin.iot.common.protoc.MessageBuf.Message();
    }

    public static com.hailin.iot.common.protoc.MessageBuf.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.hailin.iot.common.protoc.MessageBuf.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hailin_iot_common_protoc_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hailin_iot_common_protoc_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Message.protoc\022\034com.hailin.iot.common." +
      "protoc\"T\n\007Message\022\020\n\010sendUser\030\001 \001(\t\022\022\n\na" +
      "cceptUser\030\002 \001(\t\022\022\n\nmessageBit\030\003 \001(\005\022\017\n\007c" +
      "ontent\030\004 \001(\tB\014B\nMessageBufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hailin_iot_common_protoc_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hailin_iot_common_protoc_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hailin_iot_common_protoc_Message_descriptor,
        new java.lang.String[] { "SendUser", "AcceptUser", "MessageBit", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
