// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.protoc

package com.hailin.iot.common.protoc;

public final class UserBuf {
  private UserBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hailin.iot.common.protoc.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>int64 ip = 3;</code>
     * @return The ip.
     */
    long getIp();

    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>int64 logic = 5;</code>
     * @return The logic.
     */
    long getLogic();

    /**
     * <code>int64 lastMessageId = 6;</code>
     * @return The lastMessageId.
     */
    long getLastMessageId();
  }
  /**
   * Protobuf type {@code com.hailin.iot.common.protoc.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hailin.iot.common.protoc.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      userName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 24: {

              ip_ = input.readInt64();
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
            case 40: {

              logic_ = input.readInt64();
              break;
            }
            case 48: {

              lastMessageId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailin.iot.common.protoc.UserBuf.internal_static_com_hailin_iot_common_protoc_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailin.iot.common.protoc.UserBuf.internal_static_com_hailin_iot_common_protoc_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailin.iot.common.protoc.UserBuf.User.class, com.hailin.iot.common.protoc.UserBuf.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private long ip_;
    /**
     * <code>int64 ip = 3;</code>
     * @return The ip.
     */
    public long getIp() {
      return ip_;
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    public static final int LOGIC_FIELD_NUMBER = 5;
    private long logic_;
    /**
     * <code>int64 logic = 5;</code>
     * @return The logic.
     */
    public long getLogic() {
      return logic_;
    }

    public static final int LASTMESSAGEID_FIELD_NUMBER = 6;
    private long lastMessageId_;
    /**
     * <code>int64 lastMessageId = 6;</code>
     * @return The lastMessageId.
     */
    public long getLastMessageId() {
      return lastMessageId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (ip_ != 0L) {
        output.writeInt64(3, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      if (logic_ != 0L) {
        output.writeInt64(5, logic_);
      }
      if (lastMessageId_ != 0L) {
        output.writeInt64(6, lastMessageId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (ip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      if (logic_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, logic_);
      }
      if (lastMessageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, lastMessageId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailin.iot.common.protoc.UserBuf.User)) {
        return super.equals(obj);
      }
      com.hailin.iot.common.protoc.UserBuf.User other = (com.hailin.iot.common.protoc.UserBuf.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (getIp()
          != other.getIp()) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getLogic()
          != other.getLogic()) return false;
      if (getLastMessageId()
          != other.getLastMessageId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIp());
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + LOGIC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLogic());
      hash = (37 * hash) + LASTMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastMessageId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailin.iot.common.protoc.UserBuf.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailin.iot.common.protoc.UserBuf.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hailin.iot.common.protoc.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hailin.iot.common.protoc.User)
        com.hailin.iot.common.protoc.UserBuf.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailin.iot.common.protoc.UserBuf.internal_static_com_hailin_iot_common_protoc_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailin.iot.common.protoc.UserBuf.internal_static_com_hailin_iot_common_protoc_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailin.iot.common.protoc.UserBuf.User.class, com.hailin.iot.common.protoc.UserBuf.User.Builder.class);
      }

      // Construct using com.hailin.iot.common.protoc.UserBuf.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        userName_ = "";

        ip_ = 0L;

        port_ = 0;

        logic_ = 0L;

        lastMessageId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailin.iot.common.protoc.UserBuf.internal_static_com_hailin_iot_common_protoc_User_descriptor;
      }

      @java.lang.Override
      public com.hailin.iot.common.protoc.UserBuf.User getDefaultInstanceForType() {
        return com.hailin.iot.common.protoc.UserBuf.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailin.iot.common.protoc.UserBuf.User build() {
        com.hailin.iot.common.protoc.UserBuf.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailin.iot.common.protoc.UserBuf.User buildPartial() {
        com.hailin.iot.common.protoc.UserBuf.User result = new com.hailin.iot.common.protoc.UserBuf.User(this);
        result.id_ = id_;
        result.userName_ = userName_;
        result.ip_ = ip_;
        result.port_ = port_;
        result.logic_ = logic_;
        result.lastMessageId_ = lastMessageId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailin.iot.common.protoc.UserBuf.User) {
          return mergeFrom((com.hailin.iot.common.protoc.UserBuf.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailin.iot.common.protoc.UserBuf.User other) {
        if (other == com.hailin.iot.common.protoc.UserBuf.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.getIp() != 0L) {
          setIp(other.getIp());
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getLogic() != 0L) {
          setLogic(other.getLogic());
        }
        if (other.getLastMessageId() != 0L) {
          setLastMessageId(other.getLastMessageId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailin.iot.common.protoc.UserBuf.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailin.iot.common.protoc.UserBuf.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 2;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 2;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 2;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private long ip_ ;
      /**
       * <code>int64 ip = 3;</code>
       * @return The ip.
       */
      public long getIp() {
        return ip_;
      }
      /**
       * <code>int64 ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(long value) {
        
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = 0L;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 4;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private long logic_ ;
      /**
       * <code>int64 logic = 5;</code>
       * @return The logic.
       */
      public long getLogic() {
        return logic_;
      }
      /**
       * <code>int64 logic = 5;</code>
       * @param value The logic to set.
       * @return This builder for chaining.
       */
      public Builder setLogic(long value) {
        
        logic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 logic = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogic() {
        
        logic_ = 0L;
        onChanged();
        return this;
      }

      private long lastMessageId_ ;
      /**
       * <code>int64 lastMessageId = 6;</code>
       * @return The lastMessageId.
       */
      public long getLastMessageId() {
        return lastMessageId_;
      }
      /**
       * <code>int64 lastMessageId = 6;</code>
       * @param value The lastMessageId to set.
       * @return This builder for chaining.
       */
      public Builder setLastMessageId(long value) {
        
        lastMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lastMessageId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastMessageId() {
        
        lastMessageId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hailin.iot.common.protoc.User)
    }

    // @@protoc_insertion_point(class_scope:com.hailin.iot.common.protoc.User)
    private static final com.hailin.iot.common.protoc.UserBuf.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailin.iot.common.protoc.UserBuf.User();
    }

    public static com.hailin.iot.common.protoc.UserBuf.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailin.iot.common.protoc.UserBuf.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hailin_iot_common_protoc_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hailin_iot_common_protoc_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013User.protoc\022\034com.hailin.iot.common.pro" +
      "toc\"d\n\004User\022\n\n\002id\030\001 \001(\003\022\020\n\010userName\030\002 \001(" +
      "\t\022\n\n\002ip\030\003 \001(\003\022\014\n\004port\030\004 \001(\005\022\r\n\005logic\030\005 \001" +
      "(\003\022\025\n\rlastMessageId\030\006 \001(\003B\tB\007UserBufb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hailin_iot_common_protoc_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hailin_iot_common_protoc_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hailin_iot_common_protoc_User_descriptor,
        new java.lang.String[] { "Id", "UserName", "Ip", "Port", "Logic", "LastMessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
